name: tests

on:
  push:
    branches:
      - main

jobs:
  run_tests:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.2'
      - name: Update Swift tools
        run: sudo xcode-select --switch /Applications/Xcode_13.2.app && swift package update
      - name: Run tests
        run: xcodebuild test -scheme impracticalint -project impracticalint.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 12,id:dvtdevice-DVTiPhone13-iphoneos:15.0' | xcpretty && exit ${PIPESTATUS[0]}
